# My favorite pytorch functions

Pytorch is python library which extends the functionality of numpy to building regression models. A functions that I picked in order to share what I have learnt.

- tensor.stack
- tensor.randn
- tensor.abs
- tensor.add
- tensor.var

Before we begin, let's install and import PyTorch

In [1]:
# Import torch and other required modules
import torch
import numpy as np

## Function 1 - torch.stack

Concatenates a sequence of tensors along a new dimension.

In [2]:
x=np.array([[3, 5],[7,8]])
print(type(x))
print(x.dtype)

<class 'numpy.ndarray'>
int64


In [3]:
z=torch.tensor([[4,5],[9,1]])
w=torch.tensor([[8,2],[0,2]])
print(z.shape)

torch.Size([2, 2])


In [4]:
y=torch.from_numpy(x)
y.dtype
y

tensor([[3, 5],
        [7, 8]])

In [5]:
# Example 1 - working
#torch.stack(y,z,w)
a=torch.stack((y,z,w),dim=2)
print(a)

tensor([[[3, 4, 8],
         [5, 5, 2]],

        [[7, 9, 0],
         [8, 1, 2]]])


The above example takes multiple tensors of similar dimensions and stack them up along n dimension as per the sequence given in the first argument. There is a lot of difference depending on which dimension we choose.

In [6]:
# Example 2 - working
m=torch.tensor([4])
n=torch.tensor([12])
o=torch.tensor([9.4])
p=torch.tensor([923299])
q=torch.stack((m,n,o,p),dim=-2)
print(q)

tensor([[4.0000e+00],
        [1.2000e+01],
        [9.4000e+00],
        [9.2330e+05]])


Here I am trying to show how 4 of 0 dimension type tensors are stacked up to make 1 tensor. When we give dimension 1, the results are shown in a single horizontal line as opposed to vertical spacing. Dimensions of -2 to 1 are applicable to the dimension argument. 

In [7]:
# Example 3 - breaking (to illustrate when it breaks)

q=torch.stack((m,n,o,p),dim=2)
print(q)

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

Obviously if we are using 1 dimension tensors to stack up, we cannot cannot use 2 as the output tensors dimension

This is a great function to stack up tensors of similar dimensions with a desired output dimension

Let's save our work using Jovian before continuing.

In [8]:
!pip install jovian --upgrade --quiet

In [9]:
import jovian

In [10]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/idlidosalover/01-tensor-operations


'https://jovian.ai/idlidosalover/01-tensor-operations'

## Function 2 - tensor.randn

Generate a tensor with random numbers as its elements.

In [11]:
# Example 1 - working
d=torch.randn(3)
print(d,d.dtype)

tensor([-0.1625,  1.0940,  0.6623]) torch.float32


This generates a 3x1 tensor of random numbers.

In [12]:
# Example 2 - working
e=torch.randn(4,5)
e

tensor([[-1.1165,  0.4516, -0.8592, -0.8532,  1.1238],
        [-0.2762, -0.2476, -0.6454,  1.2331,  0.6159],
        [ 1.0396, -0.5196, -0.3231, -0.6574, -0.1730],
        [ 0.7680, -0.2845, -0.7876,  0.3364, -0.0400]])

This generates a 4x5 matrix of random numbers

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
f=torch.randn()

TypeError: randn() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
 * (tuple of ints size, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)


The function requires at least 1 valid argument for it to work. 

randn function is a greate way to generate a matrix of random numbers for a desired dimension.

In [14]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/idlidosalover/01-tensor-operations


'https://jovian.ai/idlidosalover/01-tensor-operations'

## Function 3 - torch.abs

This function calculates the absolute value for all elements in a tensor

In [15]:
# Example 1 - working
t1=torch.tensor([4.5, -6.98232, -29238.0001, 98237237.21212])
t2=torch.abs(t1)
print(t2)

tensor([4.5000e+00, 6.9823e+00, 2.9238e+04, 9.8237e+07])


Absolute values are nothing but values without the positive/negative signs. 

In [16]:
# Example 2 - working
t3=torch.abs(torch.tensor([0,-34, 9232,-239328]))
print(t3)

tensor([     0,     34,   9232, 239328])


Returns absolute values

In [17]:
# Example 3 - breaking (to illustrate when it breaks)
t4=torch.abs(torch.tensor())

TypeError: tensor() missing 1 required positional arguments: "data"

Invalid data arguments will break the function

abs argument is a simple and easy to calculate the absolute values for a given tensor

In [18]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/idlidosalover/01-tensor-operations


'https://jovian.ai/idlidosalover/01-tensor-operations'

## Function 4 - torch.add

This function helps us to add a scalar(or another tensor) to all the elements of the tensor

In [19]:
# Example 1 - working
t5=torch.tensor([-12,98.23,334,0])
t6=torch.add(t5,1)
print(t6)

tensor([-11.0000,  99.2300, 335.0000,   1.0000])


The value 1 is added to all the elements in the tensor

In [20]:
# Example 2 - working
t7=torch.tensor([[34,92],[65,12]])
t8=torch.add(t7, 0.5)
print(t8)

tensor([[34.5000, 92.5000],
        [65.5000, 12.5000]])


this example added a float to a all-integer tensor and returns a float tensor

In [21]:
# Example 3 - breaking (to illustrate when it breaks)
t7=torch.add(t5,t8)
print(t7)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

This example tries to add tensors of different dimensions and as a result will break.

great function to sum up tensors and scalars

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Function 5 - TORCH.VAR


This function calculates the variance of all the elements in a given tensor

In [ ]:
# Example 1 - working
var1=torch.var(t8)
print(var1)

1228.9166 is the variance of all the elements in the tensor t8 which was created above

In [ ]:
# Example 2 - working
print(torch.var(e,dim=1),"the shape of tensor e is :",e.shape)

In this example, we use a 4x5 matrix and calculate variance along a particular dimension. That is why we see multiple values in the resultant tensor.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
print(torch.var(t7))


In [ ]:
print("the type of t7 tensor is",t7.dtype,type(t7))

Apparently torch.var function supports a particular data type (which is not very intuitive imho). t7 is int64 data type. 

This function needs to be used with caution since it seems to be supporting specific data types and not others.

In [ ]:
jovian.commit(project='01-tensor-operations')

## Conclusion

We covered fairly simple and useful pytorch functions which can be used during the course of working with multiple tensors.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html


In [ ]:
jovian.commit(project='01-tensor-operations')