
# Five math functions from high school.


### Let me know if you find my selection of functions interesting

Numpy (along with pandas) are the top #1 libraries for python+datascience enthusiasts

- isfinite() - this checks if each element in a numpy array is infinite or NaN
- logical_and() - this function calculates the and operation result of each corresponding element in 2 arrays
- gcd() - this function takes 2 arguments calculates the greatest common divisor
- log10() - this function takes a integer argument and calculates the (is it decimal??) logarithm.
- lcm() - this calculates the least common multiple for the given set of arguments



In [25]:
!pip install jovian --upgrade -q

In [26]:
import jovian

In [29]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/idlidosalover/numpy-array-operations


'https://jovian.ml/idlidosalover/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [30]:
import numpy as np

In [31]:
# List of functions explained 
function1 = np.isfinite  # (change this)
function2 = np.logical_and
function3 = np.gcd
function4 = np.log10
function5 = np.lcm

## Function 1 - np.isfinite() 

this checks each element in the array for finiteness and NaN (invalid or missing number)

In [32]:
#example 1  
arr1 = [[1, 2], 
        [3, 4.]]
np.isfinite(arr1)

array([[ True,  True],
       [ True,  True]])

In [33]:
#example2
arr2 = [[5, np.NaN, 7], 
        [8, 9, 10]]
np.isfinite(arr2)

array([[ True, False,  True],
       [ True,  True,  True]])

In [34]:
#example3 - this breaks but documentation does not show it
np.isfinite([np.log(-1.),1.,np.log(0)])

<ipython-input-34-4d7c478c4a48>:2: RuntimeWarning: invalid value encountered in log
  np.isfinite([np.log(-1.),1.,np.log(0)])
<ipython-input-34-4d7c478c4a48>:2: RuntimeWarning: divide by zero encountered in log
  np.isfinite([np.log(-1.),1.,np.log(0)])


array([False,  True, False])

Clearly the decimal logarithm of negative number does not make any sense and hence the code breaks.

In [35]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/idlidosalover/numpy-array-operations


'https://jovian.ml/idlidosalover/numpy-array-operations'

The function breaks while using division by zero as an argument. 

This function can be used to check individual elements of an array

## Function 2 - np.islogical_and() 

function calculates the result of AND operation of the corresponding elements in two arrays

In [36]:
# Example 1 - working
arr1 = [[1, 2,8], 
        [3, 4.,0]]

arr2 = [[5, 6, 7], 
        [8, 9, 10]]

np.logical_and(arr1, arr2)

array([[ True,  True,  True],
       [ True,  True, False]])

In the above example, the value in the 0th position of the 0th array of arr1 is multiplied with 0th position of the 0th array of arr2 (note that the examples have 2 arrays of 3 elements each). The resultant array is checked if each individual element is True or False (integer or 0)

In [37]:
# Example 2 - working
arr1=[[-3,0.56,9],[0.0004,12012,-912]]
arr2=[[4,998,0],[9898,3266,0.0292]]
np.logical_and(arr1,arr2)

array([[ True,  True, False],
       [ True,  True,  True]])

Explanation about example

In [38]:
# Example 3 - breaking (to illustrate when it breaks)
arr1=[[-3,0.56,9],[0.0004,12012,-912]]
arr2=[[4,998],[9898,3266,0.0292]]
np.logical_and(arr1,arr2)

<ipython-input-38-45e9fbe0845b>:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  np.logical_and(arr1,arr2)


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

Obviously in the above example, the dimensions of the 2 arrays are not the same. The dimensions of both arrays must be same for this to work. As per the docs, broadcasting can be done for 1 of the 2 arrays in the event that the dimensions do not match.

This function can be used to check the boolean multiplication between 2 arguments

In [39]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/idlidosalover/numpy-array-operations


'https://jovian.ml/idlidosalover/numpy-array-operations'

## Function 3 - gcd()

gcd() calculates the greatest common divisor between the given arguments

In [40]:
# Example 1 - working
np.gcd(34,20)

2

34 can be divide by 1,2,17 and itself. 20 can be divided by 1,2,4,5,10 and itself. So 2 is the gcd.

In [41]:
# Example 2 - working
np.gcd(np.array([23,121,545]),np.array([989,33,23]))

array([23, 11,  1])

Explanation about example

In [42]:
# Example 3 - breaking (to illustrate when it breaks)
np.gcd(np.array([23,121]),np.array([989,33,23]))

ValueError: operands could not be broadcast together with shapes (2,) (3,) 

Again the arrays have different size and cannot be used together

Arrays when having different sizes need to be broadcasted.

In [43]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/idlidosalover/numpy-array-operations


'https://jovian.ml/idlidosalover/numpy-array-operations'

## Function 4 - log10()

Calculates the decimal logarithm of the integer arguments provided

In [44]:
# Example 1 - working
np.log(200)

5.298317366548036

Calculates the logarithm for an integer input

In [46]:
# Example 2 - working
np.log(9823.1212)

9.192494191988246

Calculates the logarithm value for float input

In [47]:
# Example 3 - breaking (to illustrate when it breaks)
np.log(-10)

<ipython-input-47-47864986063d>:2: RuntimeWarning: invalid value encountered in log
  np.log(-10)


nan

The logarithmic function does not like -ve integers as input arguments

It is best to check the sign (+ve or -ve) before providing it as an argument to the log function to avoid errors.

In [48]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/idlidosalover/numpy-array-operations


'https://jovian.ml/idlidosalover/numpy-array-operations'

## Function 5 - lcm()

lcm() calculates the least common multiple of the given arguments

In [49]:
# Example 1 - working
np.lcm(200,45)

1800

1800 is the least common multiple of 200 and 45

In [50]:
# Example 2 - working
np.lcm(9,12)

36

36 is the lcm of 9 and 12

In [51]:
# Example 3 - breaking (to illustrate when it breaks)
np.lcm(2.5,0.5)

UFuncTypeError: ufunc 'lcm' did not contain a loop with signature matching types (dtype('float64'), dtype('float64')) -> dtype('float64')

lcm() function does not work for float arguments

Maybe the arguments can be passed to a round function prior to passing to a lcm function

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [24]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "idlidosalover/numpy-array-operations" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/idlidosalover/numpy-array-operations


'https://jovian.ml/idlidosalover/numpy-array-operations'